export const PROFILE_IS_FETCHING = "PROFILE_IS_FETCHING";
export const PROFILE_IS_FETCHED = "PROFILE_IS_FETCHED";
export const PROFILE_FETCH_ERROR = "PROFILE_FETCH_ERROR";

export const PROFILE_EDIT = "PROFILE_EDIT"
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS"
export const PROFILE_EDIT_ERROR = "PROFILE_EDIT_ERROR"