export const FRIENDS_ARE_FETCHING = "FRIENDS_ARE_FETCHING";
export const FRIENDS_ARE_FETCHED = "FRIENDS_ARE_FETCHED";
export const FRIENDS_FETCH_ERROR = "FRIENDS_FETCH_ERROR";
export const REFRESH_DATA = "REFRESH_DATA";

export const FRIENDS_REQUESTS_ARE_FETCHED = "FRIENDS_REQUESTS_ARE_FETCHED";
export const FRIENDS_REQUESTS_ARE_FETCHING ="FRIENDS_REQUESTS_ARE_FETCHING";
export const FRIENDS_REQUESTS_ERROR = "FRIENDS_REQUESTS_ERROR";

export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const DECLINE_FRIEND_REQUEST = "DECLINE_FRIEND_REQUEST";
