export const FRIENDS_ARE_FETCHING = "FRIENDS_ARE_FETCHING";
export const FRIENDS_ARE_FETCHED = "FRIENDS_ARE_FETCHED";
export const FRIENDS_FETCH_ERROR = "FRIENDS_FETCH_ERROR";
export const REFRESH_DATA = "REFRESH_DATA";