export const LOCATIONS_ARE_FETCHING = "LOCATIONS_ARE_FETCHING";
export const LOCATIONS_ARE_FETCHED = "LOCATIONS_ARE_FETCHED";
export const LOCATIONS_FETCH_ERROR = "LOCATION_FETCH_ERROR";
export const SET_LOCATION= "SET_LOCATION";
export const LOCATION_ADD_ERROR = "LOCATION_ADD_ERROR"
export const LOCATION_ADD_SUCCESS= "LOCATION_ADD_SUCCESS";
export const LOCATION_ADD = "LOCATION_ADD";
export const LOCATION_EDIT_ERROR = "LOCATION_EDIT_ERROR"
export const LOCATION_EDIT_SUCCESS = "LOCATION_EDIT_SUCCESS";
export const LOCATION_EDIT = "LOCATION_EDIT";


export const FIELDS_ARE_FETCHING = "FIELDS_ARE_FETCHING";
export const FIELDS_ARE_FETCHED = "FIELDS_ARE_FETCHED";
export const FIELDS_FETCH_ERROR = "FIELDS_FETCH_ERROR"; 
export const FIELD_ADD_ERROR = "FIELD_ADD_ERROR"
export const FIELD_ADD_SUCCESS = "FIELD_ADD_SUCCESS";
export const FIELD_ADD = "FIELD_ADD";

export const REFRESH_DATA = "REFRESH_DATA";