export const LOCATIONS_ARE_FETCHING = "LOCATIONS_ARE_FETCHING";
export const LOCATIONS_ARE_FETCHED = "LOCATIONS_ARE_FETCHED";
export const LOCATIONS_FETCH_ERROR = "LOCATION_FETCH_ERROR";
export const SET_LOCATION= "SET_LOCATION";


export const FIELDS_ARE_FETCHING = "FIELDS_ARE_FETCHING";
export const FIELDS_ARE_FETCHED = "FIELDS_ARE_FETCHED";
export const FIELDS_FETCH_ERROR = "FIELDS_FETCH_ERROR";
